### ISSUE TITLE
Missing error information after the domains removal

### ISSUE THREAD

**Issue by pofider** [pofider/node-script-manager#12]
We've removed deprecated node.js domains from the `http-strategy` but unfortunately it seems there was significant reason for them.

If the script currently badly fails in async, it kills the whole worker process and we don't propagate the real problem cause back to the caller. This was originally handled by the domains, where just the domain crashed, we got the error and send it to the caller.

This can be replicated on this failing test
https://github.com/jsreport/jsreport-scripts/blob/master/test/scriptsTest.js#L77

**Comment by pofider** [comment]
Could we get the error message somehow in the workers manager and provide it to the caller? Otherwise user gets just meaning less error - ECONRESET

**Comment by bjrmatos** [comment]
after a research, unfortunately there is no way to caught that kind of error without using domains, or at least the behaviour would need to change.. meaning that we would need to collect all running request in an array and when an 'uncaughtException' is found in the worker we would need to respond all running requests with the error, in that way the worker process won't die but the behaviour will be misleading because you will have the chance to have an error coming from a completely different request.

we are doing our best to keep away from deprecated node.js APIs but maybe for this use case we should probably keep using domains, after reading the [node.js docs about domains](https://nodejs.org/api/domain.html), the module is in **pending deprecation**, meaning that they won't remove that module until they find a replacement (the replacement would likely be [async-hooks](https://github.com/nodejs/node-eps/blob/master/006-asynchooks-api.md)) so i think we can safely use domain and migrate later when the new API is landed.

i will prepare the changes in a PR for your approbation.

**Comment by bjrmatos** [comment]
reminder: make sure to [enable this test again](https://github.com/jsreport/jsreport-scripts/blob/master/test/scriptsTest.js#L77) after updating the version of `script-manager`

**Comment by pofider** [comment]
Ok, I see, thanks for investigation.
